Repository Trustroots/trustroots, pull requests merged in 2018-11, with the labels that each got.

#789 Rename test data to seed data
  INSTALL-DOCKER.md
  INSTALL.md
  package.json
Labels: build, in progress

#723 Create a reference (API)
  config/env/default.js
  config/env/test.js
  config/lib/worker.js
  modules/core/server/services/email.server.service.js
  modules/core/server/services/push.server.service.js
  modules/core/server/views/email-templates-text/reference-notification-first.server.view.html
  modules/core/server/views/email-templates-text/reference-notification-second.server.view.html
  modules/core/server/views/email-templates/reference-notification-first.server.view.html
  modules/core/server/views/email-templates/reference-notification-second.server.view.html
  modules/core/tests/server/worker.tests.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/server/jobs/references-publish.server.job.js
  modules/references/server/models/reference.server.model.js
  modules/references/server/policies/references.server.policy.js
  modules/references/server/routes/reference.server.routes.js
  modules/references/tests/server/reference-create.server.routes.tests.js
  modules/references/tests/server/reference.server.jobs.tests.js
  modules/references/tests/server/reference.server.model.tests.js
Labels: Module:References, [Priority] High, server, trust

#774 Add button to open location in app for mobile devices
  modules/core/client/app/init.js
  modules/offers/client/directives/tr-offer-host-view.client.directive.js
  modules/offers/client/views/directives/tr-offer-host-view.client.view.html
Labels: Module:Users, [Type] enhancement, mobile

#700 Support email subject with username and name
  modules/core/server/services/email.server.service.js
  modules/core/tests/server/services/email.server.service.tests.js
Labels: Module:Support, emails

#830 Remove dublicate firebase dependency
  package-lock.json
  package.json
Labels: build

#831 Add more username change -tests
  modules/users/tests/server/user-profile.server.routes.tests.js
Labels: Module:Users, tests

#846 Fix `aHrefSanitizationWhitelist`
  modules/core/client/app/init.js
Labels: AngularJS, [Type] Bug

#847 Improve developer experience with Node based environment checks
  bin/.eslintrc.js
  bin/ensure-config-exists.js
  bin/install-deps.js
  package.json
Labels: build

#761 Read reference by id (API)
  modules/references/server/controllers/reference.server.controller.js
  modules/references/server/policies/references.server.policy.js
  modules/references/server/routes/reference.server.routes.js
  modules/references/tests/server/reference-create.server.routes.tests.js
  modules/references/tests/server/reference-read-many.server.routes.tests.js
  modules/references/tests/server/reference-read-one.server.routes.tests.js
Labels: Module:References

#615 work in progress: server/client/contact list: Show location info about your friends
  modules/contacts/client/views/directives/tr-contact.client.view.html
  modules/contacts/server/controllers/contacts.server.controller.js
Labels: Module:Contacts

#848 Integrate message-center module to the app
  config/assets/default.js
  modules/core/client/app/config.js
  modules/core/client/directives/message-center.client.directive.js
  modules/core/client/services/message-center-client.service.js
  package-lock.json
  package.json
Labels: AngularJS, [Type] Bug, build

#850 Update dependencies
  package-lock.json
  package.json
Labels: build

#851 Move upload dir pre-check from Gulp to NPM scripts
  bin/ensure-uploads-dir-exists.js
  gulpfile.js
  package.json
Labels: build

#852 Build: name functions for better visibility to Gulp tasks
  gulpfile.js
Labels: build

#853 Build: prefix scripts and styles tasks with `build:` for clarity
  gulpfile.js
Labels: build

#871 Stats: simplify snapshot statistics
  modules/statistics/server/controllers/statistics.server.controller.js
  modules/statistics/server/jobs/daily-statistics.server.job.js
  modules/statistics/tests/server/jobs/daily-statistics.server.job.tests.js
Labels: statistics

#874 Invitations: remove invite page and redirect it to `signup`
  config/lib/express.js
  modules/users/client/config/users.client.routes.js
  modules/users/client/controllers/invite.client.controller.js
Labels: Module:Users

#883 security.txt #882
  SECURITY.md
  public/.well-known/security.txt
Labels: security

#872 more ansible stuff
  ansible/README.md
  ansible/files/authorized_keys
  ansible/files/authorized_keys_NDA-signed
  ansible/files/authorized_keys_no-NDA.j2
  ansible/files/prod-backup-scripts/backup-sync.sh
  ansible/files/prod-backup-scripts/dump-influxdb.sh
  ansible/files/prod-backup-scripts/dump-mongodb.sh
  ansible/files/prod-backup-scripts/logs.sh
  ansible/files/prod-ci/ci-deploy.conf
  ansible/files/prod-ci/ci-deploy.sh
  ansible/files/prod-ci/ci-help.sh
  ansible/files/prod-ci/ci-restart-worker.sh
  ansible/files/prod-ci/ci-restart.sh
  ansible/files/prod-ci/ci-status.sh
  ansible/files/prod-ci/ci-switch-trustroots-to-current.sh
  ansible/files/prod-ci/ci-switch-trustroots-to-latest.sh
  ansible/files/prod-ci/ci-switch-trustroots-to-previous.sh
  ansible/files/prod-conf/nginx-acme-challenge.conf
  ansible/files/prod-conf/nginx-grafana.conf
  ansible/files/prod-conf/nginx-gzip.conf
  ansible/files/prod-conf/nginx-http-passenger.conf
  ansible/files/prod-conf/nginx-influxdb.conf
  ansible/files/prod-conf/nginx-location.conf
  ansible/files/prod-conf/nginx-maintenance.conf
  ansible/files/prod-conf/nginx-passenger.conf
  ansible/files/prod-conf/nginx-shop.conf
  ansible/files/prod-conf/nginx-ssl.conf
  ansible/files/prod-conf/nginx-trustroots_org.conf
  ansible/files/prod-public-assets/maintenance.html
  ansible/files/prod-public-assets/maintenance.svg
  ansible/hosts
  ansible/playbooks/hetznerinit.yml
  ansible/playbooks/trdev.yml
  ansible/playbooks/trstaging.yml
  ansible/roles/guaka/tasks/main.yml
  ansible/roles/system/vars/main.yml
  ansible/roles/trdev/tasks/main.yml
  ansible/roles/trprod/tasks/main.yml
  ansible/roles/trustroots/tasks/main.yml
Labels: server
