Repository Trustroots/trustroots, pull requests merged in 2018-12, with the labels that each got.

#790 Add React and an example component
  .eslintrc.js
  config/lib/express.js
  config/webpack/.eslintrc.js
  config/webpack/entries/main.js
  config/webpack/webpack.config.js
  modules/core/client/app/config.js
  modules/core/client/directives/tr-boards.client.directive.js
  modules/core/client/services/photos.service.js
  modules/pages/client/components/Volunteering.component.js
  modules/pages/client/config/pages.client.routes.js
  modules/pages/client/views/volunteering.client.view.html
  modules/pages/tests/client/pages.client.routes.tests.js
  modules/users/client/components/ProfileViewBasics.component.js
  modules/users/client/views/profile/profile-view-basics.client.view.html
  package-lock.json
  package.json
Labels: framework

#909 Signup flow emails: fix typo
  modules/core/server/services/email.server.service.js
  modules/users/tests/server/jobs/user-finish-signup.server.job.tests.js
Labels: texts

#756 #746 - Give time for highlight to change
  modules/users/client/controllers/profile.client.controller.js
Labels: [Type] Bug

#929 Docs: add index
  docs/CNAME
  docs/README.md
Labels: docs

#813 Rewrite References api in ES9
  .eslintrc.js
  config/webpack/entries/pushMessagingServiceWorker.js
  modules/core/client/app/config.js
  modules/core/client/directives/tr-boards.client.directive.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/server/jobs/references-publish.server.job.js
  modules/references/server/models/reference.server.model.js
  modules/references/server/policies/references.server.policy.js
  modules/references/server/routes/reference.server.routes.js
  modules/references/tests/server/reference-create.server.routes.tests.js
  modules/references/tests/server/reference-read-many.server.routes.tests.js
  modules/references/tests/server/reference-read-one.server.routes.tests.js
  modules/references/tests/server/reference.server.jobs.tests.js
  modules/references/tests/server/reference.server.model.tests.js
  testutils/data.server.testutils.js
Labels: [Type] enhancement, framework

#531 Search users: API
  config/env/default.js
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/server/models/user.server.model.js
  modules/users/server/policies/users.server.policy.js
  modules/users/server/routes/users.server.routes.js
  modules/users/tests/server/search-users.server.routes.tests.js
Labels: Module:Users, [Priority] Normal

#938 Fixed `gulp run fontello` not working
  gulpfile.js
Labels: build

#841 Add link to profile in automated emails
  modules/core/server/services/email.server.service.js
  modules/core/server/views/email-templates/email.server.view.html
  modules/users/tests/server/jobs/user-welcome-sequence-first.server.job.tests.js
  modules/users/tests/server/jobs/user-welcome-sequence-second.server.job.tests.js
  modules/users/tests/server/jobs/user-welcome-sequence-third.server.job.tests.js
Labels: emails

#955 Add to docs how to access server from another device
  INSTALL.md
Labels: docs

#921 Internationalization (i18n) with react-i18next
  .eslintrc.js
  config/env/default.js
  config/env/test.js
  config/lib/express.js
  config/lib/i18n.js
  modules/core/client/components/LanguageSwitch.component.js
  modules/core/server/views/partials/header.server.view.html
  modules/pages/client/components/Volunteering.component.js
  modules/users/client/components/ProfileViewBasics.component.js
  package-lock.json
  package.json
  public/locales/cze/translation.json
  public/locales/cze/user-profile.json
  public/locales/cze/volunteering.json
  public/locales/eng/translation.json
  public/locales/eng/user-profile.json
  public/locales/eng/volunteering.json
Labels: React, [Needs] Design, framework, i18n

#967 Axios and docs
  docs/React.md
  package-lock.json
  package.json
Labels: React

#928 Improve email templates for References
  config/env/development.js
  modules/core/server/services/email.server.service.js
  modules/core/server/views/email-templates-text/reference-notification-first.server.view.html
  modules/core/server/views/email-templates-text/reference-notification-second.server.view.html
  modules/core/server/views/email-templates/email-with-container.server.view.html
  modules/core/server/views/email-templates/reference-notification-first.server.view.html
  modules/core/server/views/email-templates/reference-notification-second.server.view.html
Labels: Module:References

#962 Save user's locale to database (API)
  .eslintrc.js
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/server/models/user.server.model.js
  modules/users/tests/server/user-change-locale.server.routes.tests.js
  testutils/data.server.testutils.js
Labels: i18n

#981 Configs: remove process.env
  .eslintrc.js
  config/env/default.js
  config/env/development.js
  config/env/local.docker.js
  config/env/local.sample.js
  config/env/production.js
  config/env/test.js
Labels: framework

#986 Travis CI: run lint and build in the same container
  .travis.yml
  package.json
Labels: build, tests

#987 Refactor email templates to extend email-with-container
  modules/core/server/views/email-templates/confirm-contact.server.view.html
  modules/core/server/views/email-templates/email-confirmation.server.view.html
  modules/core/server/views/email-templates/messages-unread.server.view.html
  modules/core/server/views/email-templates/reactivate-hosts.server.view.html
  modules/core/server/views/email-templates/remove-profile-confirmed.server.view.html
  modules/core/server/views/email-templates/remove-profile.server.view.html
  modules/core/server/views/email-templates/reset-password-confirm.server.view.html
  modules/core/server/views/email-templates/reset-password.server.view.html
  modules/core/server/views/email-templates/signup-reminder.server.view.html
  modules/core/server/views/email-templates/signup.server.view.html
  modules/core/server/views/email-templates/welcome-sequence-first.server.view.html
  modules/core/server/views/email-templates/welcome-sequence-second.server.view.html
  modules/core/server/views/email-templates/welcome-sequence-third.server.view.html
Labels: emails

#827 Create Reference React
  .eslintrc.js
  config/lib/express.js
  modules/core/client/less/global-variables.less
  modules/references/client/api/references.api.js
  modules/references/client/components/CreateReference.component.js
  modules/references/client/components/create-reference/Info.js
  modules/references/client/components/create-reference/Interaction.js
  modules/references/client/components/create-reference/Navigation.js
  modules/references/client/components/create-reference/Recommend.js
  modules/references/client/components/create-reference/Report.js
  modules/references/client/less/reference-new.less
  modules/references/tests/client/CreateReference.client.component.tests.js
  modules/references/tests/client/Interaction.client.component.tests.js
  modules/references/tests/client/Navigation.client.component.tests.js
  modules/references/tests/client/Recommend.client.component.tests.js
  modules/references/tests/client/Report.client.component.tests.js
  modules/users/client/config/users.client.routes.js
  modules/users/client/views/profile/profile-view-references.client.view.html
  modules/users/client/views/profile/profile-view.client.view.html
  package-lock.json
  package.json
Labels: Module:References, React, [Needs] tests, trust

#993 Validate capital letters in tribe name
  modules/tribes/server/models/tribe.server.model.js
  modules/tribes/tests/server/tribes.server.model.tests.js
Labels: Module:Tribes, tests

#902 Add command line options for seeding
  INSTALL.md
  bin/fillTestData/Messages.js
  bin/fillTestData/Tribes.js
  bin/fillTestData/Users.js
  package-lock.json
  package.json
Labels: [Status] in progress, build

#997 Rewrite avatar for React
  modules/users/client/components/Avatar.component.js
  modules/users/client/views/profile/profile-view-basics.client.view.html
Labels: Module:Users, React, [Status] ready for review

#990 Refactor eslint out from Gulpfile
  .eslintignore
  .eslintrc.js
  .gitignore
  .travis.yml
  INSTALL.md
  gulpfile.js
  package-lock.json
  package.json
Labels: [Status] ready for review, build

#1008 Helper to wire up react-i18next and react-to-angular components
  .eslintrc.js
  modules/core/client/utils/i18n-angular-load.js
  modules/users/client/components/Avatar.component.js
Labels: React, [Status] ready for review, i18n

#983 Eslint: dynamicly load React version
  .eslintrc.js
  package-lock.json
  package.json
Labels: [Status] ready for review, build

#1010 Chore: upgrade dependencies
  package-lock.json
  package.json
Labels: [Status] ready for review, build

#980 Translate components of ReferencesNew
  config/lib/i18n.js
  modules/references/client/components/CreateReference.component.js
  modules/references/client/components/create-reference/Info.js
  modules/references/client/components/create-reference/Interaction.js
  modules/references/client/components/create-reference/Navigation.js
  modules/references/client/components/create-reference/Recommend.js
  modules/references/client/components/create-reference/Report.js
  modules/references/tests/client/CreateReference.client.component.tests.js
  modules/references/tests/client/Navigation.client.component.tests.js
  public/locales/cze/reference.json
Labels: React, [Status] ready for review, i18n

#1011 Check for user id before modifying offer
  modules/offers/server/controllers/offers.server.controller.js
  modules/offers/tests/server/offer.server.routes.tests.js
  package.json
Labels: Module:Offers, [Priority] High, [Type] Bug, security

#1014 Include user._id in user search API results
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/tests/server/search-users.server.routes.tests.js
Labels: Module:Users

#965 Search users
  modules/core/client/fonts/fontello/LICENSE.txt
  modules/core/client/fonts/fontello/config.json
  modules/core/client/fonts/fontello/css/tricons-codes.css
  modules/core/client/fonts/fontello/css/tricons-embedded.css
  modules/core/client/fonts/fontello/css/tricons-ie7-codes.css
  modules/core/client/fonts/fontello/css/tricons-ie7.css
  modules/core/client/fonts/fontello/css/tricons.css
  modules/core/client/fonts/fontello/demo.html
  modules/core/client/fonts/fontello/font/tricons.eot
  modules/core/client/fonts/fontello/font/tricons.svg
  modules/core/client/fonts/fontello/font/tricons.ttf
  modules/core/client/fonts/fontello/font/tricons.woff
  modules/core/client/fonts/fontello/font/tricons.woff2
  modules/search/client/components/SearchUsers.component.js
  modules/search/client/components/UsersList.js
  modules/search/client/config/search.client.routes.js
Labels: [Status] ready for review

#1021 Gulp: remove Fontello config watch
  gulpfile.js
Labels: build
