Repository Trustroots/trustroots, pull requests merged in 2018-10, with the labels that each got.

#706 Update installation instructions to reflect mongodb upgrade.
  INSTALL.md
Labels: in progress

#707 Update dependencies
  package-lock.json
  package.json
Labels: in progress

#709 Add debugging section to install guide (#702)
  INSTALL.md
Labels: docs

#714 Upgrade sinon
  modules/core/tests/server/worker.tests.js
  modules/messages/tests/server/jobs/message-unread.server.job.tests.js
  modules/messages/tests/server/message-stat-integration.server.service.tests.js
  modules/messages/tests/server/message-to-stats-integration.server.service.tests.js
  modules/sparkpost/tests/server/sparkpost-webhooks.server.controller.tests.js
  modules/statistics/tests/server/jobs/daily-statistics.server.job.tests.js
  modules/stats/tests/server/services/influx.server.service.tests.js
  modules/stats/tests/server/services/stathat.server.service.tests.js
  modules/stats/tests/server/services/stats.server.service.tests.js
  modules/stats/tests/server/stats-api-integration.server.tests.js
  modules/users/tests/server/user-lastseen.server.tests.js
  modules/users/tests/server/user-removal.server.routes.tests.js
  package-lock.json
  package.json
Labels: tests

#724 #722 Updated the NASA GIBS fallback call
  modules/core/client/services/maplayers.client.service.js
Labels: in progress

#733 Update Karma & Jasmine
  modules/users/tests/client/authentication.client.controller.tests.js
  modules/users/tests/client/password-forgot.client.controller.tests.js
  modules/users/tests/client/password-reset.client.controller.tests.js
  package-lock.json
  package.json
Labels: build, in progress, tests

#734 Fix/auth client test
  modules/users/client/controllers/authentication.client.controller.js
  modules/users/client/services/authentication.client.service.js
  modules/users/tests/client/authentication.client.controller.tests.js
Labels: [Type] Bug, in progress, tests

#737 Resolving missing ;
  .eslintrc.js
  modules/core/server/services/push.server.service.js
  modules/core/tests/server/core.server.config.tests.js
  modules/offers/client/controllers/offer-meet-list.client.controller.js
  modules/offers/tests/server/offer-search.server.routes.tests.js
  modules/statistics/tests/server/statistics.server.routes.tests.js
Labels: build

#739 Update Bower dependencies
  bower.json
Labels: build, in progress

#738 Profile: add non-binary gender
  modules/users/client/views/profile/profile-edit-about.client.view.html
  modules/users/server/models/user.server.model.js
Labels: Module:Users, [Type] enhancement, in progress

#725 Fix spelling and grammar in doc
  INSTALL-DOCKER.md
  INSTALL.md
  README.md
Labels: docs

#720 Show User Not Found in client
  modules/users/client/config/users.client.routes.js
Labels: Module:Users, in progress

#758 code of conduct
  CODE_OF_CONDUCT.md
Labels: in progress

#772 Profile: remove deprecated URL
  modules/users/client/config/users.client.routes.js
Labels: in progress

#777 Tribes: allow HTML in tribe descriptions
  modules/tribes/client/views/tribe.client.view.html
Labels: Module:Tribes, [Type] enhancement, in progress

#776 Set autocapitalize off for password field
  modules/users/client/views/authentication/signin.client.view.html
  modules/users/client/views/authentication/signup.client.view.html
Labels: Module:Users, [Type] Bug

#740 Better db seeding 462 part2
  INSTALL.md
  bin/fillTestData/Messages.js
  bin/fillTestData/Tribes.js
  bin/fillTestData/Users.js
  bin/fillTestData/data/Cities.json
  package.json
  scripts/fillTestData.js
  scripts/fillTestTribesData.js
Labels: build

#788 Search: update CSP rules for new tile addresses
  config/lib/express.js
Labels: [Type] Bug, in progress

#773 Updates to fix text zoom issue
  modules/tribes/client/less/tribe.less
  modules/tribes/client/views/tribe.client.view.html
Labels: Module:Tribes

#787 Test data: optimize mock content for less emails
  bin/fillTestData/Messages.js
  bin/fillTestData/Users.js
Labels: [Type] Bug, in progress

#784 Switch from bower to webpack
  .bowerrc
  .gitignore
  .travis.yml
  Dockerfile
  INSTALL.md
  bower.json
  config/assets/default.js
  config/assets/development.js
  config/assets/production.js
  config/assets/test.js
  config/config.js
  config/lib/express.js
  config/webpack/.eslintrc.js
  config/webpack/entries/main.js
  config/webpack/entries/pushMessagingServiceWorker.js
  config/webpack/webpack.config.js
  config/webpack/webpack.shims.js
  gulpfile.js
  karma.conf.js
  modules/core/client/app/config.js
  modules/core/client/img/angular-chosen-localytics/spinner.gif
  modules/core/client/img/chosen-js/chosen-sprite.png
  modules/core/client/img/chosen-js/chosen-sprite@2x.png
  modules/core/client/less/modules/chosen.less
  modules/core/client/services/firebase-messaging.client.service.js
  modules/core/server/views/layout.server.view.html
  package-lock.json
  package.json
  public/push-messaging-sw.js
Labels: build, in progress
