Repository Trustroots/trustroots, pull requests merged in 2018-08, with the labels that each got.

#619 Update Engines for supported Node.js versions
  package.json
Labels: devtools

#620 Remove `nsp` check from Travis CI
  .travis.yml
Labels: devtools

#604 Add testing for Node.js v10 in Travis
  .nvmrc
  .travis.yml
  INSTALL.md
  package.json
Labels: devtools

#622 Update/remove basics from gulpfile
  bin/db-drop.js
  bin/db-maintenance/archive-done-agenda-jobs.js
  gulpfile.js
  package.json
  scripts/agendash-dev
Labels: devtools

#628 Fix tests watching
  gulpfile.js
Labels: bug, devtools

#629 Split user CRUD tests into multiple files
  modules/users/tests/server/user-invite.server.routes.tests.js
  modules/users/tests/server/user-password.server.routes.tests.js
  modules/users/tests/server/user-profile.server.routes.tests.js
  modules/users/tests/server/user-signup-validate.server.routes.tests.js
  modules/users/tests/server/user-signup.server.routes.tests.js
  modules/users/tests/server/user-tribe.server.routes.tests.js
  modules/users/tests/server/user.server.routes.tests.js
Labels: tests

#631 Update CSP headers
  config/lib/express.js
Labels: Facebook

#632 Fix gulp task `build:prod`
  config/assets/default.js
  gulpfile.js
Labels: devtools

#650 Offers: split offer tests to two files
  modules/offers/tests/server/offer-search.server.routes.tests.js
  modules/offers/tests/server/offer.server.routes.tests.js
Labels: Module:Offers, tests

#651 Tests: drop database before mocha tests to ensure clean base
  bin/db-drop.js
  config/lib/mongoose.js
  gulpfile.js
Labels: devtools, tests

#653 Search: add last-seen filter
  modules/offers/server/controllers/offers.server.controller.js
  modules/offers/tests/server/offer-search.server.routes.tests.js
  modules/offers/tests/server/offer.server.routes.tests.js
  modules/search/client/controllers/search.client.controller.js
  modules/search/client/services/filters.client.service.js
  modules/search/client/views/search-sidebar-filters.client.view.html
Labels: Module:Search, enhancement

#655 Allow `updated` user property via API
  modules/users/client/directives/tr-avatar.client.directive.js
  modules/users/server/controllers/users.profile.server.controller.js
Labels: Module:Users

#645 Remove un-used `user_friends` FB API scope
  modules/users/server/routes/auth.server.routes.js
Labels: Facebook

#657 Update FB API version for oAuth
  config/lib/facebook-api.js
  modules/users/server/config/strategies/facebook.js
Labels: Facebook

#661 Add more info about MailDev and AgendaSH
  INSTALL.md
Labels: build

#664 Search: relabel "people to meet" to "meetups"
  modules/search/client/directives/tr-types-toggle.client.directive.js
  modules/search/client/views/search-sidebar-filters.client.view.html
Labels: Module:Offers, Module:Search, texts

#665 Welcome sequence: update copy for all 3 emails
  modules/core/server/services/email.server.service.js
  modules/core/server/views/email-templates-text/partials/socialmedia.server.view.html
  modules/core/server/views/email-templates-text/welcome-sequence-first.server.view.html
  modules/core/server/views/email-templates-text/welcome-sequence-second.server.view.html
  modules/core/server/views/email-templates-text/welcome-sequence-third.server.view.html
  modules/core/server/views/email-templates/partials/socialmedia.server.view.html
  modules/core/server/views/email-templates/welcome-sequence-first.server.view.html
  modules/core/server/views/email-templates/welcome-sequence-second.server.view.html
  modules/core/server/views/email-templates/welcome-sequence-third.server.view.html
  modules/users/tests/server/jobs/user-welcome-sequence-first.server.job.tests.js
  modules/users/tests/server/jobs/user-welcome-sequence-second.server.job.tests.js
Labels: Module:Users, emails, texts
