Repository Trustroots/trustroots, pull requests merged in 2019-11, with the labels that each got.

#1118 Update to Node.js 12 (LTS)
  .nvmrc
  .travis.yml
  Dockerfile
Labels: build

#1120 fix failing test script
  package.json
Labels: [Status] ready for review, tests

#1060 Migrate panel with avatar and basic user info to React
  modules/users/client/components/Avatar.component.js
  modules/users/client/components/ProfileOverview.component.js
  modules/users/client/components/ProfileViewBasics.js
  modules/users/client/controllers/profile.client.controller.js
  modules/users/client/views/profile/profile-view-basics.client.view.html
Labels: Module:Users, React

#1061 Migrate bottom navigation for small screens to React
  modules/users/client/components/BottomNavigationSmall.component.js
  modules/users/client/views/profile/profile-view.client.view.html
Labels: Module:Users, React, i18n

#1124 Fix failing confirm-contact because of a wrong api request
  modules/contacts/client/config/contacts.client.routes.js
  modules/contacts/tests/client/contacts.client.routes.tests.js
Labels: AngularJS, Module:Contacts, [Status] ready for review, [Type] Bug

#1125 Update dependencies
  package-lock.json
  package.json
Labels: build

#1121 Refactor RemoveContact logic and Contact component
  modules/contacts/client/components/Contact.js
  modules/contacts/client/components/ContactListPresentational.js
  modules/contacts/client/components/RemoveContact.js
  modules/contacts/client/components/RemoveContactContainer.js
Labels: Module:Contacts, React, [Status] ready for review

#1128 Fix a few no-redeclare issues
  .eslintrc.js
  bin/db-maintenance/archive-done-agenda-jobs.js
  modules/core/client/services/message-center-client.service.js
  modules/core/client/services/native-app-bridge.client.service.js
  modules/core/tests/server/core.server.config.tests.js
  modules/offers/server/controllers/offers.server.controller.js
  modules/users/server/controllers/users.profile.server.controller.js
Labels: build

#1129 Remove un-used Angular eslint config
  .eslintrc-angular.js
Labels: build

#1127 Fix eslint `no-prototype-builtins` issues
  config/config.js
  modules/references/server/controllers/reference.server.controller.js
  modules/sparkpost/server/controllers/sparkpost-webhooks.server.controller.js
  modules/stats/server/services/stats.server.service.js
Labels: [Status] ready for review

#1130 Replaced "Delete Request" by "Decline Request" contact requests
  modules/contacts/client/components/ContactPresentational.js
  modules/contacts/client/views/directives/tr-contact.client.view.html
  modules/users/client/views/profile/profile-view.client.view.html
Labels: Module:Contacts, texts
