Repository Trustroots/trustroots, pull requests merged in 2020-05, with the labels that each got.

#1434 Search filter: enable "online in the past 6 months" by default
  modules/search/client/services/filters.client.service.js
Labels: Module:Search, [Status] ready for review, [Type] enhancement

#1448 Update/prettier less yml
  docker-compose.yml
  modules/core/client/components/Map/map.less
  modules/core/client/less/bootstrap/badge.less
  modules/core/client/less/bootstrap/buttons.less
  modules/core/client/less/bootstrap/dropdown.less
  modules/core/client/less/bootstrap/forms.less
  modules/core/client/less/bootstrap/nav.less
  modules/core/client/less/bootstrap/navbar.less
  modules/core/client/less/bootstrap/panels.less
  modules/core/client/less/bootstrap/tables.less
  modules/core/client/less/directives/editor.less
  modules/core/client/less/directives/notification-badge.less
  modules/core/client/less/directives/placeholder.less
  modules/core/client/less/global-variables.less
  modules/core/client/less/layout/board.less
  modules/core/client/less/layout/footer.less
  modules/core/client/less/layout/header.less
  modules/core/client/less/layout/helpers.less
  modules/core/client/less/layout/layout.less
  modules/core/client/less/layout/logo.less
  modules/core/client/less/layout/spinner.less
  modules/core/client/less/layout/typography.less
  modules/core/client/less/modules/chosen.less
  modules/core/client/less/modules/icons.less
  modules/core/client/less/modules/leaflet.less
  modules/core/client/less/modules/loading-bar.less
  modules/core/client/less/modules/ui-view.less
  modules/messages/client/less/inbox.less
  modules/messages/client/less/thread.less
  modules/offers/client/less/edit.less
  modules/pages/client/less/common.less
  modules/pages/client/less/faq.less
  modules/pages/client/less/home.less
  modules/references/client/less/reference-new.less
  modules/search/client/less/cluster.less
  modules/search/client/less/map.less
  modules/search/client/less/message.less
  modules/search/client/less/search-place.less
  modules/search/client/less/sidebar-toggle.less
  modules/search/client/less/sidebar.less
  modules/tribes/client/less/tribe.less
  modules/tribes/client/less/tribes-grid.less
  modules/tribes/client/less/tribes.less
  modules/users/client/less/authentication.less
  modules/users/client/less/monkeybox.less
  modules/users/client/less/profile-edit.less
  modules/users/client/less/profile-view.less
  modules/users/client/less/signup-tribe-suggestions.less
  package.json
Labels: [Status] ready for review, build

#1447 Mobile app: improved detection
  config/lib/express.js
  modules/core/client/controllers/app.client.controller.js
  modules/core/client/services/native-app-bridge.client.service.js
  modules/core/server/views/layout.server.view.html
  modules/core/tests/server/core.server.routes.tests.js
Labels: [Status] ready for review, mobile

#1412 Migrates pages module
  modules/core/client/components/Board.js
  modules/core/client/components/BoardCredits.js
  modules/core/client/controllers/app.client.controller.js
  modules/pages/client/components/Donate.component.js
  modules/pages/client/components/DonateHelp.component.js
  modules/pages/client/components/DonatePolicy.component.js
  modules/pages/client/components/Faq.component.js
  modules/pages/client/components/FaqFoundation.component.js
  modules/pages/client/components/FaqGeneral.component.js
  modules/pages/client/components/FaqTechnology.component.js
  modules/pages/client/components/FaqTribes.component.js
  modules/pages/client/components/Foundation.component.js
  modules/pages/client/components/Guide.component.js
  modules/pages/client/components/Home.component.js
  modules/pages/client/components/ManifestoText.component.js
  modules/pages/client/components/Media.component.js
  modules/pages/client/components/Navigation.component.js
  modules/pages/client/components/Privacy.component.js
  modules/pages/client/components/Rules.component.js
  modules/pages/client/components/RulesText.component.js
  modules/pages/client/components/Team.component.js
  modules/pages/client/components/Volunteering.component.js
  modules/pages/client/config/pages.client.routes.js
  modules/pages/client/views/donate-help.client.view.html
  modules/pages/client/views/donate-policy.client.view.html
  modules/pages/client/views/donate.client.view.html
  modules/pages/client/views/faq-foundation.client.view.html
  modules/pages/client/views/faq-general.client.view.html
  modules/pages/client/views/faq-technology.client.view.html
  modules/pages/client/views/faq-tribes.client.view.html
  modules/pages/client/views/faq.client.view.html
  modules/pages/client/views/foundation.client.view.html
  modules/pages/client/views/guide.client.view.html
  modules/pages/client/views/home.client.view.html
  modules/pages/client/views/manifesto-text.client.partial.html
  modules/pages/client/views/media.client.view.html
  modules/pages/client/views/navigation.client.view.html
  modules/pages/client/views/privacy.client.view.html
  modules/pages/client/views/rules.client.view.html
  modules/pages/client/views/team.client.view.html
  modules/pages/tests/client/pages.client.routes.tests.js
  modules/tribes/client/api/tribes.api.js
  modules/tribes/client/components/TribesHeader.js
  modules/tribes/client/components/TribesPage.component.js
  modules/tribes/client/config/tribes.client.config.js
  modules/tribes/client/controllers/tribes-list.client.controller.js
  modules/tribes/tests/client/components/TribesPage.component.tests.js
Labels: React

#1473 fix misleading password hint
  modules/users/client/views/password/reset-password.client.view.html
  modules/users/client/views/profile/profile-edit-account.client.view.html
Labels: texts

#1469 fix thread votes count in admin panel
  modules/admin/server/controllers/admin.users.server.controller.js
Labels: [Status] ready for review
