Repository Trustroots/trustroots, pull requests merged in 2020-01, with the labels that each got.

#1158 Build: Add support for optional chain and null coalesce
  config/webpack/webpack.config.js
  package-lock.json
  package.json
Labels: [Status] ready for review, build

#1153 Add support team
  modules/pages/client/views/team.client.view.html
  public/img/team-dario.jpg
  public/img/team-noah.jpg
Labels: texts

#1160 Move around utils
  modules/core/client/utils/filters.js
  modules/users/client/components/AboutMe.component.js
  modules/users/client/components/ProfileViewBasics.js
  modules/users/client/components/utils/filters.js
  modules/users/client/utils/networks.js
Labels: [Status] ready for review

#1164 Tribes: Format the Tribe member count according to current language
  config/client/i18n.js
  modules/tribes/client/components/TribeItem.component.js
  public/locales/en/tribes.json
Labels: Module:Tribes, React, [Status] ready for review, i18n

#1161 Add "read more" component
  modules/core/client/components/ReadMorePanel.js
  modules/core/client/utils/filters.js
  modules/users/client/components/AboutMe.component.js
  modules/users/client/views/profile/profile-view-about.client.view.html
Labels: React, [Status] ready for review

#1171 Migrate messages inbox to react
  .travis.yml
  modules/core/client/components/TimeAgo.js
  modules/core/client/services/angular-compat.js
  modules/core/tests/client/components/TimeAgo.tests.js
  modules/messages/client/api/messages.api.js
  modules/messages/client/components/Inbox.component.js
  modules/messages/client/components/InboxThread.js
  modules/messages/client/config/messages.client.routes.js
  modules/messages/client/controllers/inbox.client.controller.js
  modules/messages/client/messages.client.module.js
  modules/messages/client/views/inbox.client.view.html
  modules/messages/tests/client/components/Inbox.component.tests.js
  modules/users/client/components/Activate.js
  modules/users/client/users.prop-types.js
  package-lock.json
  package.json
  testutils/client/data.client.testutil.js
  testutils/common/data.common.testutil.js
  testutils/server/data.server.testutil.js
Labels: React, [Status] ready for review

#1139 Remove app store buttons in native app
  modules/core/client/controllers/app.client.controller.js
  modules/pages/client/views/home.client.view.html
  modules/pages/client/views/navigation.client.view.html
Labels: [Type] enhancement, mobile

#1180 User removal: don't let suspended users remove themself
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/server/models/user.server.model.js
  modules/users/tests/server/user-removal.server.routes.tests.js
Labels: Module:Users, [Status] ready for review, security

#1179 Profiles: hide profiles with 'shadowban' role
  modules/users/server/controllers/users.authentication.server.controller.js
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/tests/server/user-profile.server.routes.tests.js
  modules/users/tests/server/user-signup.server.routes.tests.js
Labels: Module:Users, [Status] ready for review, security

#1183 Shadow ban: hide messages
  modules/messages/server/controllers/messages.server.controller.js
  modules/messages/tests/server/message.server.routes.tests.js
Labels: Module:Messages, [Status] ready for review, security

#1186 Add `moderator` role
  modules/messages/server/controllers/messages.server.controller.js
  modules/messages/tests/server/message-stat-integration.server.service.tests.js
  modules/messages/tests/server/message-to-stats-integration.server.service.tests.js
  modules/messages/tests/server/message.server.routes.tests.js
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/server/models/user.server.model.js
  modules/users/tests/server/user-profile.server.routes.tests.js
  modules/users/tests/server/user.server.model.tests.js
Labels: Module:Messages, Module:Users, [Type] enhancement, admin, security

#1185 Add shadow-ban notice to rules
  modules/pages/client/views/rules-text.client.partial.html
Labels: texts

#1187 Admin panel: add role controls
  modules/admin/client/api/users.api.js
  modules/admin/client/components/AdminSearchUsers.component.js
  modules/admin/client/components/AdminUser.component.js
  modules/admin/client/components/UserState.component.js
  modules/admin/server/controllers/admin.users.server.controller.js
  modules/admin/server/policies/admin.server.policy.js
  modules/admin/server/routes/admin.server.routes.js
  modules/admin/tests/server/admin.users.server.routes.tests.js
Labels: [Type] enhancement, admin
