Repository Trustroots/trustroots, pull requests merged in 2020-04, with the labels that each got.

#1173 Implement messages threads in react
  jest.config.js
  modules/core/client/components/TrEditor.js
  modules/core/client/filters/plain-text-length.client.filter.js
  modules/core/client/services/angular-compat.js
  modules/messages/client/api/messages.api.js
  modules/messages/client/components/Flashcard.js
  modules/messages/client/components/Inbox.component.js
  modules/messages/client/components/InfiniteMessages.js
  modules/messages/client/components/QuickReply.js
  modules/messages/client/components/Thread.component.js
  modules/messages/client/components/ThreadMessage.js
  modules/messages/client/components/ThreadMessages.js
  modules/messages/client/components/ThreadReply.js
  modules/messages/client/config/messages.client.routes.js
  modules/messages/client/controllers/inbox.client.controller.js
  modules/messages/client/controllers/thread.client.controller.js
  modules/messages/client/directives/thread-dimensions.client.directive.js
  modules/messages/client/directives/threads.client.directive.js
  modules/messages/client/less/thread.less
  modules/messages/client/messages.client.module.js
  modules/messages/client/services/messages-read.client.service.js
  modules/messages/client/services/messages.client.service.js
  modules/messages/client/views/thread.client.view.html
  modules/messages/server/controllers/messages.server.controller.js
  modules/messages/tests/client/components/Inbox.component.tests.js
  modules/messages/tests/client/components/Thread.component.tests.js
  modules/pages/client/views/faq-general.client.view.html
  modules/pages/client/views/faq.client.view.html
  modules/users/client/api/users.api.js
  modules/users/client/components/Monkeybox.js
  package-lock.json
  package.json
  testutils/client/data.client.testutil.js
  testutils/common/data.common.testutil.js
  yarn.lock
Labels: React, [Status] ready for review

#1045 User profile offers react
  config/shared/README.md
  config/shared/locales.json
  modules/core/client/utils/filters.js
  modules/core/tests/client/components/LanguageSwitch.component.tests.js
  modules/offers/client/api/offers.api.js
  modules/offers/client/components/OfferLocation.component.js
  modules/offers/client/components/Offers.component.js
  modules/offers/client/components/OffersPresentational.js
  modules/offers/client/less/view.less
  modules/users/client/views/profile/profile-view-about.client.view.html
  package-lock.json
  public/locales/cs/languages.json
  public/locales/cs/offers.json
  public/locales/en/languages.json
  public/locales/en/offers.json
  public/locales/pl/offers.json
Labels: Module:Offers, React, [Status] ready for review, i18n

#1332 Offer map: resize on window resize
  modules/core/client/components/Map/index.js
Labels: [Status] ready for review, [Type] Bug, geo

#1364 Add Tooltip component
  modules/core/client/components/Tooltip.js
  modules/offers/client/components/OffersPresentational.js
  modules/tribes/client/components/JoinButton.js
  public/locales/en/offers.json
Labels: React, [Status] ready for review

#1365 Refactor Navigation component
  modules/core/client/components/StepNavigation.js
  modules/core/client/utils/validation.js
  modules/core/tests/client/components/StepNavigation.client.component.tests.js
  modules/references/client/components/CreateReference.component.js
  modules/references/client/components/create-reference/Navigation.js
  modules/references/tests/client/components/CreateReference.client.component.tests.js
  modules/references/tests/client/components/Navigation.client.component.tests.js
Labels: React, [Status] ready for review

#1333 Map: add style control
  config/env/local.sample.js
  modules/core/client/components/Map/MapIcon.js
  modules/core/client/components/Map/MapStyleControl.js
  modules/core/client/components/Map/constants.js
  modules/core/client/components/Map/index.js
  modules/core/client/components/Map/map.less
  modules/core/client/components/Map/osm.json
  modules/offers/client/components/OfferLocation.component.js
Labels: [Status] ready for review, geo

#1405 Donate page: remove Mailchimp referral link
  modules/pages/client/views/donate.client.view.html
Labels: texts

#1370 Migrate unread message count to react
  .eslintrc.js
  modules/core/client/controllers/app.client.controller.js
  modules/core/client/core.client.module.js
  modules/core/client/directives/tr-window-blur.client.directive.js
  modules/core/client/directives/tr-window-focus.client.directive.js
  modules/core/client/less/directives/notification-badge.less
  modules/core/client/services/angular-compat.js
  modules/core/client/utils/dom.js
  modules/core/client/utils/subscribable.js
  modules/core/server/views/layout.server.view.html
  modules/core/server/views/partials/header.server.view.html
  modules/messages/client/api/messages.api.js
  modules/messages/client/components/Inbox.component.js
  modules/messages/client/components/Thread.component.js
  modules/messages/client/components/UnreadCount.component.js
  modules/messages/client/config/messages.client.run.js
  modules/messages/client/messages.client.module.js
  modules/messages/client/services/messages-count-favicon-updater.client.service.js
  modules/messages/client/services/messages-count-poll.client.service.js
  modules/messages/client/services/messages-count.client.service.js
  modules/messages/client/services/unread-message-count.client.service.js
  modules/messages/client/services/visibility.client.service.js
  modules/messages/tests/client/components/UnreadCount.component.tests.js
  modules/messages/tests/client/services/unread-message-count.client.service.tests.js
Labels: React, [Status] ready for review
