Repository Trustroots/trustroots, pull requests merged in 2020-12, with the labels that each got.

#1880 Hide "public" title unless also "pending" experiences are showing
  modules/references/client/components/ListReferences.component.js
  modules/references/client/components/read-references/ReferencesSection.js
Labels: Module:Experiences, [Status] ready for review

#1882 Experiences list: improve visuals & copy for pending experience
  modules/references/client/components/read-references/Reference.js
Labels: Module:Experiences, [Status] ready for review

#1490 api for blocking users
  modules/users/server/controllers/users.block.server.controller.js
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/server/models/user.server.model.js
  modules/users/server/policies/users.server.policy.js
  modules/users/server/routes/users-block.server.routes.js
  modules/users/tests/server/user-block.server.routes.tests.js
Labels: Module:Users, [Status] ready for review, [Type] enhancement

#1878 Rewrite "user not found" message in React
  modules/users/client/components/UserDoesNotExist.component.js
  modules/users/client/views/profile/profile-view.client.view.html
Labels: Module:Users, [Status] ready for review

#1907 Reactify "user does not exist" message
  modules/users/client/components/UserDoesNotExist.component.js
  modules/users/client/views/profile/profile-view.client.view.html
Labels: [Status] ready for review

#1909 Experiences: redesign success messages
  jest.config.js
  modules/core/client/components/SuccessMessage.js
  modules/core/client/img/sparkles.svg
  modules/references/client/components/CreateReference.component.js
  modules/references/client/components/create-reference/DuplicateInfo.js
  modules/references/client/components/create-reference/SubmittedInfo.js
  modules/references/tests/client/components/CreateReference.client.component.tests.js
Labels: Module:Experiences, [Status] ready for review

#1905 Fix: profile description field height jumping
  modules/users/client/less/profile-edit.less
Labels: Module:Users, [Status] ready for review, [Type] Bug

#1901 Profile & Experiences: simplify gender label
  modules/core/client/utils/user_info.js
  modules/references/client/components/read-references/Reference.js
  modules/users/client/components/ProfileViewBasics.js
Labels: Module:Experiences

#1896 Update: refactor experiences time
  modules/core/client/components/TimeAgo.js
  modules/references/client/components/read-references/Reference.js
Labels: Module:Experiences, [Status] ready for review

#1607 Docs: instructions for activating translation
  docs/i18n.md
Labels: docs, i18n

#1903 Experiences: always show report toggle
  modules/core/client/components/Switch.js
  modules/core/client/less/directives/switch.less
  modules/references/client/components/create-reference/Recommend.js
  modules/references/client/components/create-reference/Report.js
  modules/references/tests/client/components/CreateReference.client.component.tests.js
Labels: Module:Experiences

#1934 Update various URLs to correct versions
  .editorconfig
  CODE_OF_CONDUCT.md
  docs/Accessibility.md
  docs/Icons.md
  docs/InfluxDB.md
  docs/Install-Docker.md
  docs/Install.md
  docs/Photos.md
  docs/Volunteering.md
  docs/_layouts/default.html
  modules/pages/client/components/FaqFoundation.component.js
  modules/pages/client/components/FaqGeneral.component.js
  modules/pages/client/components/Home.component.js
Labels: docs, texts

#1933 Fix: circle images on homepage
  modules/pages/client/components/Home.component.js
Labels: [Type] Bug

#1667 References: include replies
  modules/references/client/components/CreateReference.component.js
  modules/references/client/components/ListReferences.component.js
  modules/references/client/components/read-references/Reference.js
  modules/references/client/components/read-references/ReferenceCounts.js
  modules/references/client/components/read-references/ReferencesSection.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/tests/server/reference-read-many.server.routes.tests.js
Labels: Module:Experiences

#1881 Use existing RulesText component in Angular modal
  modules/pages/client/components/RulesText.component.js
  modules/pages/client/views/rules-text.client.partial.html
  modules/users/client/views/authentication/rules-modal.client.view.html
Labels: React, [Status] ready for review

#1902 Reference list: clearer meta labels & better mobile support
  modules/references/client/components/create-reference/SubmittedInfo.js
  modules/references/client/components/read-references/Meta.js
  modules/references/client/components/read-references/Recommendation.js
  modules/references/client/components/read-references/Reference.js
  modules/references/client/utils/constants.js
Labels: Module:Experiences, [Status] ready for review

#1936 Compare references on the client based on the id rather than username
  modules/references/client/components/CreateReference.component.js
  modules/references/client/components/ListReferences.component.js
  modules/references/server/controllers/reference.server.controller.js
Labels: Module:Experiences, [Status] ready for review, [Type] enhancement

#1938 Fix title proptype warning
  modules/references/client/components/read-references/ReferencesSection.js
Labels: [Type] Bug

#1929 Home: use count prop for member count
  modules/pages/client/components/Home.component.js
Labels: i18n

#1931 Update homepage screenshots
  config/webpack/webpack.config.js
  modules/core/client/components/Screenshot.js
  modules/pages/client/components/Home.component.js
  modules/pages/client/img/README.md
  modules/pages/client/img/screenshot-profile-2x.png
  modules/pages/client/img/screenshot-profile-2x.webp
  modules/pages/client/img/screenshot-profile.png
  modules/pages/client/img/screenshot-profile.webp
  modules/pages/client/img/screenshot-search-2x.png
  modules/pages/client/img/screenshot-search-2x.webp
  modules/pages/client/img/screenshot-search.png
  modules/pages/client/img/screenshot-search.webp
  modules/pages/client/less/home.less
  public/img/screenshot-profile.png
  public/img/screenshot-profile@2x.png
  public/img/screenshot-search.png
  public/img/screenshot-search@2x.png
Labels: [Status] ready for review

#1951 Remove logged-out search page
  modules/core/client/controllers/app.client.controller.js
  modules/search/client/config/search.client.routes.js
  modules/search/client/controllers/search-signup.client.controller.js
  modules/search/client/less/signup.less
  modules/search/client/search.client.module.js
  modules/search/client/views/search-signin.client.view.html
  modules/search/tests/client/search.client.routes.tests.js
Labels: [Status] ready for review

#1955 i18n: fix plurals from few English strings
  public/locales/en/messages.json
  public/locales/en/references.json
Labels: [Type] Bug, i18n

#1952 Rename references route to experiences
  modules/core/server/services/email.server.service.js
  modules/core/server/services/push.server.service.js
  modules/references/client/components/ListReferences.component.js
  modules/references/client/components/create-reference/DuplicateInfo.js
  modules/references/client/components/create-reference/SubmittedInfo.js
  modules/references/client/components/read-references/Reference.js
  modules/references/tests/server/reference-create.server.routes.tests.js
  modules/users/client/components/TopNavigationSmall.component.js
  modules/users/client/config/users.client.routes.js
  modules/users/client/views/profile/profile-view.client.view.html
Labels: [Status] ready for review

#1930 Build: stop auto-detecting outdated dependencies
  bin/install-deps.js
  docs/Install.md
Labels: [Status] ready for review, build

#1957 Turn 404 not found page into React component
  modules/core/client/components/NotFoundPage.component.js
  modules/core/client/config/core.client.routes.js
  modules/core/client/views/404.client.view.html
Labels: React, [Status] ready for review

#1953 Update copy from references to experiences
  modules/core/server/services/push.server.service.js
  modules/references/client/components/create-reference/ReferenceToSelfInfo.js
  modules/references/tests/client/components/CreateReference.client.component.tests.js
  modules/references/tests/server/reference-create.server.routes.tests.js
  modules/users/client/config/users.client.routes.js
  modules/users/client/views/profile/profile-view.client.view.html
Labels: Module:Experiences, [Status] ready for review, texts

#1958 add gender when seeding users for test db
  bin/fillTestData/Users.js
Labels: [Status] ready for review, [Type] enhancement

#1910 create a separate endpoint to retrieve logged-in user's reference given to `userTo`
  modules/references/client/api/references.api.js
  modules/references/client/components/CreateReference.component.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/server/policies/references.server.policy.js
  modules/references/server/routes/reference.server.routes.js
  modules/references/tests/client/components/CreateReference.client.component.tests.js
  modules/references/tests/server/reference-read-mine.server.routes.tests.js
Labels: Module:Experiences, [Status] ready for review, [Type] enhancement

#1961 Tooling: adjust newsletter list export script
  bin/export-newsletter-subscribers.js
  scripts/db-maintenance/export-newsletter-subscribers.js
Labels: admin

#1960 Fix experiences tab link on the profile page
  modules/users/client/views/profile/profile-view.client.view.html
Labels: [Type] Bug

#1962 Tooling: replace non-allowed characters from newsletter export script
  bin/export-newsletter-subscribers.js
Labels: emails

#1964 Simplify /api/references endpoint by removing userFrom param
  modules/references/client/api/references.api.js
  modules/references/client/components/ListReferences.component.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/tests/server/reference-read-many.server.routes.tests.js
Labels: Module:Experiences, [Status] ready for review, [Type] enhancement

#1965 Profile: Reactify notification about email confirmation
  modules/users/client/components/ConfirmEmailNotification.component.js
  modules/users/client/views/profile/profile-view.client.view.html
Labels: Module:Users, React, [Status] ready for review

#1966 Profile: convert data download to React
  modules/users/client/components/DownloadProfile.component.js
  modules/users/client/views/profile/profile-edit-account.client.view.html
Labels: React, [Status] ready for review

#1963 Docs: add newsletter documentation
  docs/Newsletter.md
Labels: [Status] ready for review, docs

#1937 Add experience list indentation
  modules/references/client/components/read-references/Reference.js
  modules/references/client/components/read-references/ReferencesSection.js
  modules/users/client/components/UserLink.js
Labels: Module:Experiences, [Status] ready for review

#1968 Refactor: use flattened 'interaction' object only in react component
  modules/references/client/api/references.api.js
  modules/references/client/components/CreateReference.component.js
  modules/references/client/components/read-references/Meta.js
  modules/references/client/components/read-references/Reference.js
  modules/references/tests/client/components/CreateReference.client.component.tests.js
Labels: Module:Experiences, [Type] enhancement

#1969 Add LanguageList component and fill test users with random languages
  bin/fillTestData/Users.js
  modules/users/client/components/LanguageList.js
  modules/users/client/components/Monkeybox.js
  modules/users/client/components/ProfileViewBasics.js
Labels: [Status] ready for review

#1970 Experiences: add count to tab
  modules/core/client/components/Badge.js
  modules/references/client/api/references.api.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/server/policies/references.server.policy.js
  modules/references/server/routes/reference.server.routes.js
  modules/references/tests/server/reference-count.server.routes.tests.js
  modules/users/client/components/ProfileTabs.component.js
  modules/users/client/controllers/profile.client.controller.js
  modules/users/client/views/profile/profile-view.client.view.html
Labels: Module:Experiences, Module:Users, React, [Status] ready for review

#1979 Reference thread stats: add gender
  modules/references-thread/server/controllers/reference-thread.server.controller.js
Labels: [Status] ready for review

#1977 Refactor: return experiences paired up with responses from backend
  modules/references/client/components/ListReferences.component.js
  modules/references/client/components/read-references/Meta.js
  modules/references/client/components/read-references/Reference.js
  modules/references/client/components/read-references/ReferenceCounts.js
  modules/references/client/components/read-references/ReferencesSection.js
  modules/references/client/experiences.prop-types.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/tests/server/reference-create.server.routes.tests.js
  modules/references/tests/server/reference-read-many.server.routes.tests.js
  modules/references/tests/server/reference-read-mine.server.routes.tests.js
  modules/references/tests/server/reference-read-one.server.routes.tests.js
Labels: Module:Experiences

#1984 Admin: improved message list
  modules/admin/client/components/AdminMessages.component.js
  modules/admin/server/controllers/admin.messages.server.controller.js
Labels: [Status] ready for review, admin

#1985 Docs: update newsletter docs
  docs/Newsletter.md
Labels: docs

#1978 Convert "reference thread" feature into React
  config/webpack/entries/main.js
  modules/messages/client/components/Thread.component.js
  modules/references-thread/client/api/reference-thread.api.js
  modules/references-thread/client/components/ReferenceThread.js
  modules/references-thread/client/directives/reference-thread.client.directive.js
  modules/references-thread/client/references-thread.client.module.js
  modules/references-thread/client/services/reference-thread.client.service.js
  modules/references-thread/client/views/directives/tr-reference-thread.client.view.html
Labels: Module:Experience-thread, [Status] ready for review

#1989 Profiles: add volunteer badge
  modules/users/client/components/ProfileViewBasics.js
  modules/users/server/controllers/users.profile.server.controller.js
  modules/users/tests/server/user-profile.server.routes.tests.js
Labels: Module:Users, [Status] ready for review

#1956 Experiences: update email copy
  modules/core/server/services/email.server.service.js
  modules/core/server/services/push.server.service.js
  modules/core/server/views/email-templates-text/reference-notification-first.server.view.html
  modules/core/server/views/email-templates-text/reference-notification-second.server.view.html
  modules/core/server/views/email-templates/reference-notification-first.server.view.html
  modules/core/server/views/email-templates/reference-notification-second.server.view.html
  modules/references/server/controllers/reference.server.controller.js
  modules/references/tests/server/reference-create.server.routes.tests.js
Labels: Module:Experiences, [Status] in progress, emails

#1990 References -> Experiences: update api endpoint urls
  modules/references/client/api/references.api.js
  modules/references/server/controllers/reference.server.controller.js
  modules/references/server/policies/references.server.policy.js
  modules/references/server/routes/reference.server.routes.js
  modules/references/tests/server/reference-count.server.routes.tests.js
  modules/references/tests/server/reference-create.server.routes.tests.js
  modules/references/tests/server/reference-read-many.server.routes.tests.js
  modules/references/tests/server/reference-read-mine.server.routes.tests.js
  modules/references/tests/server/reference-read-one.server.routes.tests.js
Labels: Module:Experiences, [Status] ready for review
