Repository Trustroots/trustroots, pull requests merged in 2021-05, with the labels that each got.

#2121 Block users UI
  modules/messages/client/components/Thread.component.js
  modules/users/client/api/block.api.js
  modules/users/client/components/BlockMember.component.js
  modules/users/client/components/BlockedMemberBanner.component.js
  modules/users/client/less/profile-view.less
  modules/users/client/views/profile/profile-view-basics.client.view.html
  modules/users/client/views/profile/profile-view.client.view.html
Labels: [Type] enhancement

#2254 Update rules
  modules/pages/client/components/RulesText.component.js
Labels: texts

#2181 Copy: use localized format for date
  modules/contacts/client/components/ContactPresentational.js
  modules/contacts/client/components/RemoveContact.js
  modules/pages/client/components/Media.component.js
  modules/statistics/client/components/Statistics.component.js
  modules/users/client/components/ProfileViewBasics.js
  public/locales/cs/contacts.json
  public/locales/cs/users.json
  public/locales/de/contacts.json
  public/locales/de/users.json
  public/locales/en/contacts.json
  public/locales/en/pages.json
  public/locales/en/statistics.json
  public/locales/en/users.json
  public/locales/es/contacts.json
  public/locales/es/users.json
  public/locales/fr/contacts.json
  public/locales/fr/users.json
  public/locales/it/contacts.json
  public/locales/it/pages.json
  public/locales/it/users.json
  public/locales/nb/contacts.json
  public/locales/nb/users.json
  public/locales/pl/contacts.json
  public/locales/pl/users.json
  public/locales/pt/users.json
  public/locales/sv/contacts.json
  public/locales/sv/users.json
Labels: i18n, texts

#2255 Put more translations into production: Norwegian, Swedish, Indonesian
  config/shared/locales.json
Labels: i18n

#2175 Fix experience tab visual styles
  modules/core/client/less/global-variables.less
  modules/experiences/client/components/CreateExperience.component.js
  modules/experiences/client/less/experiences-new.less
Labels: Module:Experiences

#1991 Admin: add statistics about acquisition stories
  modules/admin/client/api/acquisition-stories.api.js
  modules/admin/client/components/AdminAcquisitionStories.component.js
  modules/admin/client/components/AdminAcquisitionStoriesAnalysis.component.js
  modules/admin/client/components/AdminAcquisitionStoriesMenu.js
  modules/admin/client/components/AdminHeader.component.js
  modules/admin/client/config/admin.client.routes.js
  modules/admin/server/controllers/admin.acquisition-stories.server.controller.js
  modules/admin/server/policies/admin.server.policy.js
  modules/admin/server/routes/admin.server.routes.js
  modules/admin/tests/server/admin.acquisition-stories.server.routes.tests.js
  package-lock.json
  package.json
Labels: admin, statistics

#1993 Tests: clear all DB collections between tests runs & use abstraction everywhere
  modules/admin/tests/server/admin.messages.server.routes.tests.js
  modules/contacts/tests/server/contact.server.model.tests.js
  modules/contacts/tests/server/contact.server.routes.tests.js
  modules/core/tests/server/core.server.config.tests.js
  modules/messages/tests/server/message-stat-integration.server.service.tests.js
  modules/messages/tests/server/message-stat.server.model.tests.js
  modules/messages/tests/server/message-stat.server.routes.tests.js
  modules/messages/tests/server/message-stat.server.service.tests.js
  modules/messages/tests/server/message-to-stats-integration.server.service.tests.js
  modules/messages/tests/server/message-to-stats.server.service.tests.js
  modules/messages/tests/server/message.server.model.tests.js
  modules/messages/tests/server/message.server.routes.tests.js
  modules/offers/tests/server/offer-search.server.routes.tests.js
  modules/offers/tests/server/offer.server.model.tests.js
  modules/offers/tests/server/offer.server.routes.tests.js
  modules/references-thread/tests/server/reference-thread.server.model.tests.js
  modules/references-thread/tests/server/reference-thread.server.routes.tests.js
  modules/statistics/tests/server/statistics.server.routes.tests.js
  modules/support/tests/server/model.server.model.tests.js
  modules/tribes/tests/server/tribes.server.model.tests.js
  modules/tribes/tests/server/tribes.server.routes.tests.js
  modules/users/tests/server/search-users.server.routes.tests.js
  modules/users/tests/server/user-lastseen.server.tests.js
  modules/users/tests/server/user-password.server.routes.tests.js
  modules/users/tests/server/user-profile.server.routes.tests.js
  modules/users/tests/server/user-removal.server.routes.tests.js
  modules/users/tests/server/user-signup-validate.server.routes.tests.js
  modules/users/tests/server/user-signup.server.routes.tests.js
  modules/users/tests/server/user-tribe.server.routes.tests.js
  modules/users/tests/server/user.server.model.tests.js
  testutils/server/data.server.testutil.js
Labels: tests

#2275 Improved acquisition-story analysis
  modules/admin/server/controllers/admin.acquisition-stories.server.controller.js
  modules/admin/tests/server/admin.acquisition-stories.server.routes.tests.js
Labels: admin

#2267 Locales: add Chinese
  config/shared/locales.json
Labels: i18n

#2332 Rewrite small bits of Angular in React
  modules/offers/client/components/MeetsExplanation.component.js
  modules/offers/client/components/NoMeets.component.js
  modules/offers/client/views/offer-meet-edit.client.view.html
  modules/offers/client/views/offer-meet-list.client.view.html
Labels: Module:Offers, React

#2333 Languages: add a few missing locales
  config/shared/locales.json
Labels: i18n
