Repository Trustroots/trustroots, pull requests merged in 2021-04, with the labels that each got.

#2192 Update migration docs
  migrations/README.md
Labels: [Status] ready for review, docs

#2177 Allow only people from my circles find me
  modules/offers/client/controllers/offer-host-edit.client.controller.js
  modules/offers/client/views/offer-host-edit.client.view.html
  modules/offers/server/controllers/offers.server.controller.js
  modules/offers/server/models/offer.server.model.js
  modules/offers/tests/server/offer-search.server.routes.tests.js
  modules/offers/tests/server/offer.server.routes.tests.js
  modules/users/server/models/user.server.model.js
Labels: Module:Offers, [Status] ready for review

#2133 Remove/angular directive host offer
  modules/offers/client/directives/tr-offer-host-view.client.directive.js
  modules/offers/client/offers.client.module.js
  modules/offers/client/views/directives/tr-offer-host-view.client.view.html
  modules/users/client/views/profile/profile-view-accommodation.client.view.html
Labels: AngularJS, React, [Status] ready for review

#2219 Mobile navigation: minor translation bug fix
  modules/pages/client/components/Navigation.component.js
Labels: [Type] Bug, i18n

#2108 Sentry: add Mongo/Mongoose integration
  config/env/default.js
  config/lib/app.js
  package.json
Labels: build

#2223 Dependencies: remove un-used imports-loader
  package-lock.json
  package.json
Labels: build

#2237 Experiences: enable by default
  config/env/default.js
Labels: Module:Experiences

#2234 i18n: change Moment locale on language change
  config/client/i18n.js
Labels: [Status] ready for review, i18n

#2217 i18n: remove feature flag
  config/env/default.js
  config/env/development.js
  config/env/test.js
  config/lib/express.js
  docs/i18n.md
  modules/core/server/views/partials/header.server.view.html
  modules/users/client/views/profile/profile-edit-account.client.view.html
Labels: [Status] ready for review

#2171 Reactify header
  docs/React.md
  modules/core/client/components/AppHeader.component.js
  modules/core/client/components/LanguageSwitch.js
  modules/core/client/components/NavigationLoggedIn.js
  modules/core/client/components/NavigationLoggedOut.js
  modules/core/client/components/NavigationMenuItem.js
  modules/core/client/components/NavigationSubMenuList.js
  modules/core/client/controllers/app.client.controller.js
  modules/core/client/less/layout/header.less
  modules/core/server/views/partials/header.server.view.html
  modules/core/tests/client/components/LanguageSwitch.tests.js
  modules/users/client/components/InterfaceLanguagePanel.component.js
Labels: React, [Status] ready for review

#2244 Husky: remove running `npm test` on pre-commit hook
  .husky/pre-commit
  package.json
Labels: build
